export const mapping = {
  1: { search: true, signer: true },
  2: { search: true, signer: true },
  3: { search: true, week_signer: true },
  4: { search: true, week_signer: true },
  5: { search: true },
  6: { search: true },
  7: { search: false },
  8: { search: false },
  9: { search: false },
  10: { search: true },
  11: { search: false },
  12: { search: false },
  13: { search: true },
  14: { search: false },
  15: { search: false },
  16: { search: false },
  17: { search: false },
  18: { search: false },
  19: { search: false },
  20: { search: false },
  21: { search: false },
  22: { search: false },
  23: { search: false },
  24: { search: false },
  25: { search: true, signer: true },
  26: { search: true },
  27: { search: false },
  28: { search: false },
  29: { search: true, signer: true },
  30: { search: true },
  31: { search: true, signer: true },
  32: { search: false },
  33: { search: false },
  34: { search: false },
  35: { search: false },
  36: { search: true },
  37: { search: true },
  38: { search: true },
  39: { search: false },
  40: { search: false },
  41: { search: true },
  42: { search: false },
  43: { search: false },
  44: { search: false },
  45: { search: true },
  46: { search: false },
  47: { search: false },
  48: { search: false },
  49: { search: true },
  50: { search: false },
  51: { search: false },
  52: { search: false },
  53: { search: true },
  54: { search: false },
  55: { search: false },
  56: { search: false },
}
