export const mapping = {
  1: { search: true, signer: true },
  2: { search: true, signer: true },
  3: { search: true, week_signer: true },
  4: { search: true, week_signer: true },
  5: { search: false },
  6: { search: false },
  7: { search: false },
  8: { search: false },
  9: { search: false },
  10: { search: false },
  11: { search: false },
  12: { search: false },
  13: { search: false },
  14: { search: false },
  15: { search: false },
  16: { search: false },
  17: { search: false },
  18: { search: false },
  19: { search: true, signer: true },
  20: { search: true },
  21: { search: false },
  22: { search: false },
  23: { search: true, signer: true },
  24: { search: true },
  25: { search: true, signer: true },
  26: { search: false },
  27: { search: false },
  28: { search: false },
  29: { search: false },
  30: { search: true },
  31: { search: true },
  32: { search: false },
  33: { search: false },
  34: { search: false },
  35: { search: true },
  36: { search: false },
  37: { search: false },
  38: { search: false },
  39: { search: true },
  40: { search: false },
  41: { search: false },
  42: { search: false },
  43: { search: true },
  44: { search: false },
  45: { search: false },
  46: { search: false },
  47: { search: false }, // { search: true },
  48: { search: false },
  49: { search: false },
  50: { search: false },
}
