export const mapping = {
  1: { search: true, signer: true },
  2: { search: true, signer: true },
  3: { search: true, week_signer: true },
  4: { search: true, week_signer: true },
  5: { search: false },
  6: { search: false, kursant: true },
  7: { search: false, kursant: true },
  8: { search: false, kursant: true },
  9: { search: false, kursant: true },
  10: { search: false, kursant: true },
  11: { search: false, kursant: true },
  12: { search: true, signer: true },
  13: { search: true },
  14: { search: true },
  15: { search: true, signer: true },
  16: { search: true },
  17: { search: true, signer: true },
  18: { search: false },
  19: { search: false },
  20: { search: false },
  21: { search: true },
  22: { search: true },
  23: { search: false },
  24: { search: false },
  25: { search: true },
  26: { search: false, kursant: true },
  27: { search: false, kursant: true },
  28: { search: true },
  29: { search: false, kursant: true },
  30: { search: false, kursant: true },
  31: { search: true },
  32: { search: false, kursant: true },
  33: { search: false, kursant: true },
  34: { search: true },
  35: { search: false, kursant: true },
  36: { search: false, kursant: true },
}
